import { Component, OnInit } from '@angular/core';
import { CountService } from '../services/count.service';

@Component({
  selector: 'elements',
  templateUrl: './elements.component.html',
  styleUrls: ['./elements.component.css']
})
export class ElementsComponent implements OnInit {

  constructor(private countService: CountService) { }

  ngOnInit() { }

  //array of objects of all elements
  eleArr = [
    {
      num: '1',
      name: 'hydrogen',
      abbr: 'H',
      class: 'element',
      showName: false,
    },
    {
      num: '',
      name: '',
      abbr: '',
      class: 'filler-xl',
      showName: false,
    },
    {
      num: '2',
      name: 'helium',
      abbr: 'He',
      class: 'element',
      showName: false,
    },
    {
      num: '3',
      name: 'lithium',
      abbr: 'Li',
      class: 'element',
      showName: false,
    },
    {
      num: '4',
      name: 'beryllium',
      abbr: 'Be',
      class: 'element',
      showName: false,
    },
    {
      num: '',
      name: '',
      abbr: '',
      class: 'filler-l',
      showName: false,
    },
    {
      num: '5',
      name: 'boron',
      abbr: 'B',
      class: 'element',
      showName: false,
    },
    {
      num: '6',
      name: 'carbon',
      abbr: 'C',
      class: 'element',
      showName: false,
    },
    {
      num: '7',
      name: 'nitrogen',
      abbr: 'N',
      class: 'element',
      showName: false,
    },
    {
      num: '8',
      name: 'oxygen',
      abbr: 'O',
      class: 'element',
      showName: false,
    },
    {
      num: '9',
      name: 'fluorine',
      abbr: 'F',
      class: 'element',
      showName: false,
    },
    {
      num: '10',
      name: 'neon',
      abbr: 'Ne',
      class: 'element',
      showName: false,
    },
    {
      num: '11',
      name: 'sodium',
      abbr: 'Na',
      class: 'element',
      showName: false,
    },
    {
      num: '12',
      name: 'magnesium',
      abbr: 'Mg',
      class: 'element',
      showName: false,
    },
    {
      num: '',
      name: '',
      abbr: '',
      class: 'filler-l',
      showName: false,
    },
    {
      num: '13',
      name: 'aluminum',
      abbr: 'Al',
      class: 'element',
      showName: false,
    },
    {
      num: '14',
      name: 'silicon',
      abbr: 'Si',
      class: 'element',
      showName: false,
    },
    {
      num: '15',
      name: 'phosphorus',
      abbr: 'P',
      class: 'element',
      showName: false,
    },
    {
      num: '16',
      name: 'sulfur',
      abbr: 'S',
      class: 'element',
      showName: false,
    },
    {
      num: '17',
      name: 'chlorine',
      abbr: 'Cl',
      class: 'element',
      showName: false,
    },
    {
      num: '18',
      name: 'argon',
      abbr: 'Ar',
      class: 'element',
      showName: false,
    },
    {
      num: '19',
      name: 'potassium',
      abbr: 'K',
      class: 'element',
      showName: false,
    },
    {
      num: '20',
      name: 'calcium',
      abbr: 'Ca',
      class: 'element',
      showName: false,
    },
    {
      num: '21',
      name: 'scandium',
      abbr: 'Sc',
      class: 'element',
      showName: false,
    },
    {
      num: '22',
      name: 'titanium',
      abbr: 'Ti',
      class: 'element',
      showName: false,
    },
    {
      num: '23',
      name: 'vanadium',
      abbr: 'V',
      class: 'element',
      showName: false,
    },
    {
      num: '24',
      name: 'chromium',
      abbr: 'Cr',
      class: 'element',
      showName: false,
    },
    {
      num: '25',
      name: 'manganese',
      abbr: 'Mn',
      class: 'element',
      showName: false,
    },
    {
      num: '26',
      name: 'iron',
      abbr: 'Fe',
      class: 'element',
      showName: false,
    },
    {
      num: '27',
      name: 'cobalt',
      abbr: 'Co',
      class: 'element',
      showName: false,
    },
    {
      num: '28',
      name: 'nickel',
      abbr: 'Ni',
      class: 'element',
      showName: false,
    },
    {
      num: '29',
      name: 'copper',
      abbr: 'Cu',
      class: 'element',
      showName: false,
    },
    {
      num: '30',
      name: 'zinc',
      abbr: 'Zn',
      class: 'element',
      showName: false,
    },
    {
      num: '31',
      name: 'gallium',
      abbr: 'Ga',
      class: 'element',
      showName: false,
    },
    {
      num: '32',
      name: 'germanium',
      abbr: 'Ge',
      class: 'element',
      showName: false,
    },
    {
      num: '33',
      name: 'arsenic',
      abbr: 'As',
      class: 'element',
      showName: false,
    },
    {
      num: '34',
      name: 'selenium',
      abbr: 'Se',
      class: 'element',
      showName: false,
    },
    {
      num: '35',
      name: 'bromine',
      abbr: 'Br',
      class: 'element',
      showName: false,
    },
    {
      num: '36',
      name: 'krypton',
      abbr: 'Kr',
      class: 'element',
      showName: false,
    },
    {
      num: '37',
      name: 'rubidium',
      abbr: 'Rb',
      class: 'element',
      showName: false,
    },
    {
      num: '38',
      name: 'strontium',
      abbr: 'Sr',
      class: 'element',
      showName: false,
    },
    {
      num: '39',
      name: 'yttrium',
      abbr: 'Y',
      class: 'element',
      showName: false,
    },
    {
      num: '40',
      name: 'zirconium',
      abbr: 'Zr',
      class: 'element',
      showName: false,
    },
    {
      num: '41',
      name: 'niobium',
      abbr: 'Nb',
      class: 'element',
      showName: false,
    },
    {
      num: '42',
      name: 'molybdenum',
      abbr: 'Mo',
      class: 'element',
      showName: false,
    },
    {
      num: '43',
      name: 'technetium',
      abbr: 'Tc',
      class: 'element',
      showName: false,
    },
    {
      num: '44',
      name: 'ruthenium',
      abbr: 'Ru',
      class: 'element',
      showName: false,
    },
    {
      num: '45',
      name: 'rhodium',
      abbr: 'Rh',
      class: 'element',
      showName: false,
    },
    {
      num: '46',
      name: 'palladium',
      abbr: 'Pd',
      class: 'element',
      showName: false,
    },
    {
      num: '47',
      name: 'silver',
      abbr: 'Ag',
      class: 'element',
      showName: false,
    },
    {
      num: '48',
      name: 'cadmium',
      abbr: 'Cd',
      class: 'element',
      showName: false,
    },
    {
      num: '49',
      name: 'indium',
      abbr: 'In',
      class: 'element',
      showName: false,
    },
    {
      num: '50',
      name: 'tin',
      abbr: 'Sn',
      class: 'element',
      showName: false,
    },
    {
      num: '51',
      name: 'antimony',
      abbr: 'Sb',
      class: 'element',
      showName: false,
    },
    {
      num: '52',
      name: 'tellurium',
      abbr: 'Te',
      class: 'element',
      showName: false,
    },
    {
      num: '53',
      name: 'iodine',
      abbr: 'I',
      class: 'element',
      showName: false,
    },
    {
      num: '54',
      name: 'xenon',
      abbr: 'Xe',
      class: 'element',
      showName: false,
    },
    {
      num: '55',
      name: 'cesium',
      abbr: 'Cs',
      class: 'element',
      showName: false,
    },
    {
      num: '56',
      name: 'barium',
      abbr: 'Ba',
      class: 'element',
      showName: false,
    },
    {
      num: '57-71',
      name: '',
      abbr: '',
      class: 'filler-m',
      showName: false,
    },
    {
      num: '72',
      name: 'hafnium',
      abbr: 'Hf',
      class: 'element',
      showName: false,
    },
    {
      num: '73',
      name: 'tantalum',
      abbr: 'Ta',
      class: 'element',
      showName: false,
    },
    {
      num: '74',
      name: 'tungsten',
      abbr: 'W',
      class: 'element',
      showName: false,
    },
    {
      num: '75',
      name: 'rhenium',
      abbr: 'Re',
      class: 'element',
      showName: false,
    },
    {
      num: '76',
      name: 'osmium',
      abbr: 'Os',
      class: 'element',
      showName: false,
    },
    {
      num: '77',
      name: 'iridium',
      abbr: 'Ir',
      class: 'element',
      showName: false,
    },
    {
      num: '78',
      name: 'platinum',
      abbr: 'Pt',
      class: 'element',
      showName: false,
    },
    {
      num: '79',
      name: 'gold',
      abbr: 'Au',
      class: 'element',
      showName: false,
    },
    {
      num: '80',
      name: 'mercury',
      abbr: 'Hg',
      class: 'element',
      showName: false,
    },
    {
      num: '81',
      name: 'thallium',
      abbr: 'Tl',
      class: 'element',
      showName: false,
    },
    {
      num: '82',
      name: 'lead',
      abbr: 'Pb',
      class: 'element',
      showName: false,
    },
    {
      num: '83',
      name: 'bismuth',
      abbr: 'Bi',
      class: 'element',
      showName: false,
    },
    {
      num: '84',
      name: 'polonium',
      abbr: 'Po',
      class: 'element',
      showName: false,
    },
    {
      num: '85',
      name: 'astatine',
      abbr: 'At',
      class: 'element',
      showName: false,
    },
    {
      num: '86',
      name: 'radon',
      abbr: 'Rn',
      class: 'element',
      showName: false,
    },
    {
      num: '87',
      name: 'francium',
      abbr: 'Fr',
      class: 'element',
      showName: false,
    },
    {
      num: '88',
      name: 'radium',
      abbr: 'Ra',
      class: 'element',
      showName: false,
    },
    {
      num: '89-103',
      name: '',
      abbr: '',
      class: 'filler-m',
      showName: false,
    },
    {
      num: '104',
      name: 'rutherfordium',
      abbr: 'Rf',
      class: 'element',
      showName: false,
    },
    {
      num: '105',
      name: 'dubnium',
      abbr: 'Db',
      class: 'element',
      showName: false,
    },
    {
      num: '106',
      name: 'seaborgium',
      abbr: 'Sg',
      class: 'element',
      showName: false,
    },
    {
      num: '107',
      name: 'bohrium',
      abbr: 'Bh',
      class: 'element',
      showName: false,
    },
    {
      num: '108',
      name: 'hassium',
      abbr: 'Hs',
      class: 'element',
      showName: false,
    },
    {
      num: '109',
      name: 'meitnerium',
      abbr: 'Mt',
      class: 'element',
      showName: false,
    },
    {
      num: '110',
      name: 'darmstadtium',
      abbr: 'Ds',
      class: 'element',
      showName: false,
    },
    {
      num: '111',
      name: 'roentgenium',
      abbr: 'Rg',
      class: 'element',
      showName: false,
    },
    {
      num: '112',
      name: 'copernicium',
      abbr: 'Cn',
      class: 'element',
      showName: false,
    },
    {
      num: '113',
      name: 'nihonium',
      abbr: 'Nh',
      class: 'element',
      showName: false,
    },
    {
      num: '114',
      name: 'flerovium',
      abbr: 'Fl',
      class: 'element',
      showName: false,
    },
    {
      num: '115',
      name: 'moscovium',
      abbr: 'Mc',
      class: 'element',
      showName: false,
    },
    {
      num: '116',
      name: 'livermorium',
      abbr: 'Lv',
      class: 'element',
      showName: false,
    },
    {
      num: '117',
      name: 'tennessine',
      abbr: 'Ts',
      class: 'element',
      showName: false,
    },
    {
      num: '118',
      name: 'oganesson',
      abbr: 'Og',
      class: 'element',
      showName: false,
    },
    {
      num: '',
      name: '',
      abbr: '',
      class: 'filler-xxl',
      showName: false,
    },
    {
      num: '',
      name: '',
      abbr: '',
      class: 'filler-s',
      showName: false,
    },
    {
      num: '57',
      name: 'lanthanum',
      abbr: 'La',
      class: 'element',
      showName: false,
    },
    {
      num: '58',
      name: 'cerium',
      abbr: 'Ce',
      class: 'element',
      showName: false,
    },
    {
      num: '59',
      name: 'praseodymium',
      abbr: 'Pr',
      class: 'element',
      showName: false,
    },
    {
      num: '60',
      name: 'neodymium',
      abbr: 'Nd',
      class: 'element',
      showName: false,
    },
    {
      num: '61',
      name: 'promethium',
      abbr: 'Pm',
      class: 'element',
      showName: false,
    },
    {
      num: '62',
      name: 'samarium',
      abbr: 'Sm',
      class: 'element',
      showName: false,
    },
    {
      num: '63',
      name: 'europium',
      abbr: 'Eu',
      class: 'element',
      showName: false,
    },
    {
      num: '64',
      name: 'gadolinium',
      abbr: 'Gd',
      class: 'element',
      showName: false,
    },
    {
      num: '65',
      name: 'terbium',
      abbr: 'Tb',
      class: 'element',
      showName: false,
    },
    {
      num: '66',
      name: 'dysprosium',
      abbr: 'Dy',
      class: 'element',
      showName: false,
    },
    {
      num: '67',
      name: 'holmium',
      abbr: 'Ho',
      class: 'element',
      showName: false,
    },
    {
      num: '68',
      name: 'erbium',
      abbr: 'Er',
      class: 'element',
      showName: false,
    },
    {
      num: '69',
      name: 'thulium',
      abbr: 'Tm',
      class: 'element',
      showName: false,
    },
    {
      num: '70',
      name: 'ytterbium',
      abbr: 'Yb',
      class: 'element',
      showName: false,
    },
    {
      num: '71',
      name: 'lutetium',
      abbr: 'Lu',
      class: 'element',
      showName: false,
    },
    {
      num: '',
      name: '',
      abbr: '',
      class: 'filler-xs',
      showName: false,
    },
    {
      num: '',
      name: '',
      abbr: '',
      class: 'filler-s',
      showName: false,
    },
    {
      num: '89',
      name: 'actinium',
      abbr: 'Ac',
      class: 'element',
      showName: false,
    },
    {
      num: '90',
      name: 'thorium',
      abbr: 'Th',
      class: 'element',
      showName: false,
    },
    {
      num: '91',
      name: 'protactinium',
      abbr: 'Pa',
      class: 'element',
      showName: false,
    },
    {
      num: '92',
      name: 'uranium',
      abbr: 'U',
      class: 'element',
      showName: false,
    },
    {
      num: '93',
      name: 'neptunium',
      abbr: 'Np',
      class: 'element',
      showName: false,
    },
    {
      num: '94',
      name: 'plutonium',
      abbr: 'Pu',
      class: 'element',
      showName: false,
    },
    {
      num: '95',
      name: 'americium',
      abbr: 'Am',
      class: 'element',
      showName: false,
    },
    {
      num: '96',
      name: 'curium',
      abbr: 'Cm',
      class: 'element',
      showName: false,
    },
    {
      num: '97',
      name: 'berkelium',
      abbr: 'Bk',
      class: 'element',
      showName: false,
    },
    {
      num: '98',
      name: 'californium',
      abbr: 'Cf',
      class: 'element',
      showName: false,
    },
    {
      num: '99',
      name: 'einsteinium',
      abbr: 'Es',
      class: 'element',
      showName: false,
    },
    {
      num: '100',
      name: 'fermium',
      abbr: 'Fm',
      class: 'element',
      showName: false,
    },
    {
      num: '101',
      name: 'mendelevium',
      abbr: 'Md',
      class: 'element',
      showName: false,
    },
    {
      num: '102',
      name: 'nobelium',
      abbr: 'No',
      class: 'element',
      showName: false,
    },
    {
      num: '103',
      name: 'lawrencium',
      abbr: 'Lr',
      class: 'element',
      showName: false,
    },
    {
      num: '',
      name: '',
      abbr: '',
      class: 'filler-s',
      showName: false,
    },
  ];

  //if the user's input matches an element name, doesn't already exist, and isn't empty, then add a score, reset the input, and show the element name
  eleGuessCheck(event) {
    this.eleArr.forEach(element => {
      if (element.name === event.target.value.toLowerCase() && element.name !== '' && element.showName === false) {
        this.countService.increment();
        element.showName = true;
        event.target.value = '';
      }
    });
  }
}
